// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7wPeSPuFYyANq9DPMb2TEh9Bdu-HmMrY',
    appId: '1:473300758797:web:33e4cb8bcc53d5e67ec044',
    messagingSenderId: '473300758797',
    projectId: 'hotel-7e2d2',
    authDomain: 'hotel-7e2d2.firebaseapp.com',
    storageBucket: 'hotel-7e2d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRtX6EFdNx0teS7lHHaG8I6w0IQbVHnMA',
    appId: '1:473300758797:android:13d5bff94d27c0357ec044',
    messagingSenderId: '473300758797',
    projectId: 'hotel-7e2d2',
    storageBucket: 'hotel-7e2d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdsrgV_he5abcPs1AjsICqUePG_Xr808M',
    appId: '1:473300758797:ios:26f56b1bd77cfe937ec044',
    messagingSenderId: '473300758797',
    projectId: 'hotel-7e2d2',
    storageBucket: 'hotel-7e2d2.appspot.com',
    iosBundleId: 'com.example.hotelManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdsrgV_he5abcPs1AjsICqUePG_Xr808M',
    appId: '1:473300758797:ios:26f56b1bd77cfe937ec044',
    messagingSenderId: '473300758797',
    projectId: 'hotel-7e2d2',
    storageBucket: 'hotel-7e2d2.appspot.com',
    iosBundleId: 'com.example.hotelManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7wPeSPuFYyANq9DPMb2TEh9Bdu-HmMrY',
    appId: '1:473300758797:web:88f9d0aabe6348ee7ec044',
    messagingSenderId: '473300758797',
    projectId: 'hotel-7e2d2',
    authDomain: 'hotel-7e2d2.firebaseapp.com',
    storageBucket: 'hotel-7e2d2.appspot.com',
  );

}