// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK8Dte6z2VCWzt3QH0hrqIprAuXwNMYFY',
    appId: '1:606738930565:web:a6a37277825709fa83c2ec',
    messagingSenderId: '606738930565',
    projectId: 'hotel-management-a8f44',
    authDomain: 'hotel-management-a8f44.firebaseapp.com',
    storageBucket: 'hotel-management-a8f44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt4U6V65TXFjwHj1-RMr9de7TGgfBD_04',
    appId: '1:606738930565:android:896647720ff8c4ec83c2ec',
    messagingSenderId: '606738930565',
    projectId: 'hotel-management-a8f44',
    storageBucket: 'hotel-management-a8f44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdiPRTqfqRzE3WRN8CxRDaDK5guNZ-Ex0',
    appId: '1:606738930565:ios:385f9aa1f6b0ccbc83c2ec',
    messagingSenderId: '606738930565',
    projectId: 'hotel-management-a8f44',
    storageBucket: 'hotel-management-a8f44.appspot.com',
    iosBundleId: 'com.example.hotelManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdiPRTqfqRzE3WRN8CxRDaDK5guNZ-Ex0',
    appId: '1:606738930565:ios:385f9aa1f6b0ccbc83c2ec',
    messagingSenderId: '606738930565',
    projectId: 'hotel-management-a8f44',
    storageBucket: 'hotel-management-a8f44.appspot.com',
    iosBundleId: 'com.example.hotelManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK8Dte6z2VCWzt3QH0hrqIprAuXwNMYFY',
    appId: '1:606738930565:web:8e4c536658d02a7883c2ec',
    messagingSenderId: '606738930565',
    projectId: 'hotel-management-a8f44',
    authDomain: 'hotel-management-a8f44.firebaseapp.com',
    storageBucket: 'hotel-management-a8f44.appspot.com',
  );
}
