// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgQQDJFIjEtb8m306MQtIvjyxEd3_cIEU',
    appId: '1:199936989549:web:a9535b41119572ced2e264',
    messagingSenderId: '199936989549',
    projectId: 'my-project-4c53b',
    authDomain: 'my-project-4c53b.firebaseapp.com',
    storageBucket: 'my-project-4c53b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkpvF5I-d_RfdONjZqUGBRwjdCrQAsxa4',
    appId: '1:199936989549:android:dc1b60b54cefd2ffd2e264',
    messagingSenderId: '199936989549',
    projectId: 'my-project-4c53b',
    storageBucket: 'my-project-4c53b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAheBlpodgn1RFyuqXoycYtZqArK5wL5oE',
    appId: '1:199936989549:ios:31dc8d70664c1d18d2e264',
    messagingSenderId: '199936989549',
    projectId: 'my-project-4c53b',
    storageBucket: 'my-project-4c53b.appspot.com',
    iosBundleId: 'com.example.dtb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAheBlpodgn1RFyuqXoycYtZqArK5wL5oE',
    appId: '1:199936989549:ios:26dffed4433ec943d2e264',
    messagingSenderId: '199936989549',
    projectId: 'my-project-4c53b',
    storageBucket: 'my-project-4c53b.appspot.com',
    iosBundleId: 'com.example.dtb.RunnerTests',
  );
}
